# Generated by Django 3.2.8 on 2022-03-01 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pcate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.maincategory'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
