# Generated by Django 4.1.7 on 2023-03-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customeraddressmodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddressmodel',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraddressmodel',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
